### ISSUE TITLE
发现一奇葩bug

### ISSUE THREAD

**Issue by lancer-wang** [zyzdai/xsgg#2]
![image](https://github.com/zyzdai/xsgg/assets/69783837/5b8d9000-7357-46dc-bee0-33878903c694)
如果软件在这个界面，然后用其他软件导入书籍
点击导入之后，无论选择什么，都不会退出这里
![image](https://github.com/zyzdai/xsgg/assets/69783837/f2593cf6-fb85-4d44-9b93-4190820af70d)

**Comment by lancer-wang** [comment]
测试多次均可复现

**Comment by zyzdai** [comment]
原版的有这个bug吗？

**Comment by zyzdai** [comment]
> 测试多次均可复现

原版有这个bug吗？

**Comment by lancer-wang** [comment]
> > 测试多次均可复现
> 
> 原版有这个bug吗？

测试了下，也有。。。
